---
# tasks file for nfsserver

- name: Create mountable dir
  file: 
       path: /share 
       state: directory 
       mode: 0777 
       owner: root 
       group: root

- name: make sure the mount drive has a filesystem
  filesystem: 
       fstype: ext4 
       dev: /dev/sdb

- name: set mountpoints
  mount: 
       name: /share 
       src: /dev/sdb
       fstype: auto 
       opts: defaults,nobootwait 
       dump: 0 
       passno: 2 
       state: mounted

- name: Ensure NFS utilities are installed.
  apt: 
       name: {{ item }} 
       state: present
  with_items:
        - nfs-common
        - nfs-kernel-server

- name: copy /etc/exports
  template: 
       src: exports.j2 
       dest: /etc/exports 
       owner: root 
       group: root

- name: restart nfs server
  service: 
       name: nfs-kernel-server 
       state: restarted

